name: deploy-github-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted, macos ]

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web --release --base-href '/byxelkroken/'
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /byxelkroken/