name: deploy-github-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web --release --base-href '/urban-rotary-phone/'
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /andreanielsen83.github.io/urban-rotary-phone/