name: flutter-snapshot

on:
  push:
    branches: [ main ]
jobs:
  flutter-snapshot-android:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cp ~/Downloads/currently_flutter.android.key.properties ./android/key.properties
      - run: flutter pub get
      - id: build_Android_prod
        run: flutter build appbundle --release --build-name 0.0.0 --build-number ${{github.run_number}}
      - run: ls -la build/app/outputs/bundle/release/app-release.aab
