name: flutter-snapshot

on:
  push:
    branches: [ main ]
jobs:
  flutter-snapshot-android:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cp ~/Downloads/currently_flutter.android.key.properties ./android/key.properties
      - run: flutter pub get
      - id: build_Android_prod
        run: flutter build appbundle --release --no-tree-shake-icons --build-name 0.0.0 --build-number ${{github.run_number}}
      - run: cp build/app/outputs/bundle/release/app-release.aab ~/Downloads/byxelkroken-0.0.0.${{github.run_number}}.aab
      - run: ls -la ~/Downloads/byxelkroken-*

  flutter-snapshot-ios:
    runs-on: [ self-hosted, macos ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - id: build_iOS_prod
        run: flutter build ipa --release --no-tree-shake-icons --build-name 0.0.0 --build-number ${{github.run_number}}
      - run: cp build/ios/ipa/currently_flutter.ipa ~/Downloads/byxelkroken-0.0.0.${{github.run_number}}.ipa
      - run: ls -la ~/Downloads/byxelkroken-*