name: flutter-release

on:
  release:
    types: [ released ]
jobs:
  flutter-release-android:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cp ~/Downloads/currently_flutter.android.key.properties ./android/key.properties
      - run: flutter pub get
      - id: build_name
        run: REF_NAME=${{github.ref_name}}; VERSION_NAME=${REF_NAME##*v}; echo "::set-output name=stripped::${VERSION_NAME%.*}"
      - id: build_Android_prod
        run: flutter build appbundle --release --build-name ${{steps.build_name.outputs.stripped}} --build-number ${{github.run_number}}
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.DEPLOY_PLAY_ACCOUNT }}
          packageName: se.stopgap.byxelkroken
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          mappingFile: build/app/outputs/mapping/release/mapping.txt
          debugSymbols: build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib

  flutter-release-ios:
    runs-on: [ self-hosted, macos ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - id: build_name
        run: REF_NAME=${{github.ref_name}}; VERSION_NAME=${REF_NAME##*v}; echo "::set-output name=stripped::${VERSION_NAME%.*}"
      - id: build_iOS_prod
        run: flutter build ipa --release --build-name ${{steps.build_name.outputs.stripped}} --build-number ${{github.run_number}}
      - run: |
          xcrun altool --upload-package build/ios/ipa/byxelkroken.ipa --type ios \
            --apple-id 6746264660 --bundle-id se.stopgap.byxelkroken \
            --bundle-version ${{github.run_number}} --bundle-short-version-string ${{steps.build_name.outputs.stripped}} \
            -p @keychain:ALTOOL_CREDENTIALS

  flutter-gh-pages:
    runs-on: [ self-hosted, macos ]

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build web --release --base-href '/byxelkroken/'
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /byxelkroken/